#!/usr/bin/env python3
"""Generate app/alert_stations_gen.h - a compact flash-resident ALERT id -> station table.

The single source of truth is the MegaNet repository (github.com/cdomotor-g/MegaNet).
Nothing from MegaNet is copied into this repository except the generated header, which is
a build artefact regenerated by CI.

Sources consumed:
  stations.json                  station records with sensors[] / alert_ids{}
  data/All 2021 Working 2.txt    the legacy ALERT "address location file" (UTF-16LE)
  data/ALL_REPEATERS.csv         repeater -> BoM network -> pass (address) ranges

Usage:
  python3 tools/gen_stations.py [--meganet-dir DIR] [--filter stations.filter] ...
  python3 tools/gen_stations.py --list-networks
  python3 tools/gen_stations.py --check          # CI: fail if the header is stale
  python3 tools/gen_stations.py --blob out.bin [--filter F | --all]
  python3 tools/gen_stations.py --check-blob out.bin [--lookup ID ...]

--blob writes the station table the radio keeps in SPI flash (V2_SPEC section 8,
uploaded with the console's STN commands) instead of the header: full names (up
to 40 characters, not 13), no size budget but the region's 128 KB. --check-blob
validates such a file without touching MegaNet: it re-checks every structural
rule the firmware relies on and runs the firmware's lookup over all 8,192
addresses.

Standard library only.
"""

import argparse
import hashlib
import csv
import io
import json
import os
import re
import struct
import subprocess
import sys
import urllib.error
import urllib.request
import zlib
from datetime import datetime, timezone

# --------------------------------------------------------------------------------------
# constants
# --------------------------------------------------------------------------------------

REPO = "cdomotor-g/MegaNet"
RAW_BASE = "https://raw.githubusercontent.com/" + REPO + "/{ref}/"
API_COMMIT = "https://api.github.com/repos/" + REPO + "/commits/{ref}"

STATIONS_JSON = "stations.json"
ADDRESS_FILE = "data/All 2021 Working 2.txt"
ADDRESS_FILE_URL = "data/All%202021%20Working%202.txt"
REPEATERS_CSV = "data/ALL_REPEATERS.csv"

# kind codes - must match the comment block emitted into the header and the C decoder
KIND_NONE = 0
KIND_RAIN = 1
KIND_LEVEL = 2
KIND_BATT = 3
KIND_REP = 4
KIND_OTHER = 5
KIND_CHECK = 6
KIND_NAME = {
    KIND_NONE: "NONE",
    KIND_RAIN: "RAIN",
    KIND_LEVEL: "LEVEL",
    KIND_BATT: "BATT",
    KIND_REP: "REP",
    KIND_OTHER: "OTHER",
    KIND_CHECK: "CHECK",
}

SITE_SPAN = 5          # a site covers base .. base+4
SITE_BYTES = 6         # sizeof(AlertSite_t)
MAX_ALERT_ID = 0x1FFF  # 13-bit ALERT address
NAME_MAX = 13
NAME_ALLOWED = re.compile(r"[^A-Z0-9 /.\-&']")

# The SPI-flash table (--blob), V2_SPEC section 8; App/app/alert_stn.c reads it.
#   header  "ASTB", u16 version, u16 count, u32 names_len,
#           u32 zlib CRC32 of everything after the header, char source[16]
#   sites   count x {u16 base_id, u16 kinds, u32 name_off}, sorted by base_id
#   names   NUL-terminated, name_off counted from the first
# All little-endian.
BLOB_MAGIC = b"ASTB"
BLOB_VERSION = 1
BLOB_HEADER = struct.Struct("<4sHHII16s")
BLOB_SITE = struct.Struct("<HHI")
BLOB_NAME_MAX = 40             # ALERT_NAME_MAX in alert_stn.h
BLOB_MAX_BYTES = 0x20000       # 0x1C0000-0x1DFFFF
BLOB_NAME_OK = re.compile(r"^[A-Z0-9 /.\-&']+$")

# Ordered classification rules. "RN/Rep" and "Rain/Rep" must land on RAIN, so rain wins
# over repeater; battery/volt is tested first because "Batt" never means anything else.
KIND_RULES = [
    (re.compile(r"batt|volt", re.I), KIND_BATT),
    (re.compile(r"rain", re.I), KIND_RAIN),
    (re.compile(r"level|stage|ahd|height|river|\bRV\b", re.I), KIND_LEVEL),
    (re.compile(r"repeat|\bRep\b", re.I), KIND_REP),
    (re.compile(r"check|chk", re.I), KIND_CHECK),
]

# Trailing tokens that are not part of the site name: the sensor-kind markers used by the
# address file, plus the "AL"/"ALERT" marker most MegaNet names carry ("Loudoun Br AL").
SUFFIX_TOKEN = re.compile(
    r"^(batt(ery)?|rn|rain|rv|river|rep(eater)?[0-9]?|rptr|r/rep|rn/rep|rain/rep|"
    r"chk|check|v|volts?|temp|rh|lvl|stage|ahd|al|alert)$",
    re.I,
)

# Address-file suffix tokens are terse and do not all fall out of KIND_RULES ("RN" is
# rain, not other; "RN/Rep" is rain, not repeater), so map the known ones explicitly.
SUFFIX_KIND = {
    "rn": KIND_RAIN, "rain": KIND_RAIN, "rn/rep": KIND_RAIN, "rain/rep": KIND_RAIN,
    "r/rep": KIND_RAIN,
    "rv": KIND_LEVEL, "river": KIND_LEVEL, "lvl": KIND_LEVEL, "stage": KIND_LEVEL,
    "ahd": KIND_LEVEL,
    "batt": KIND_BATT, "battery": KIND_BATT, "v": KIND_BATT, "volt": KIND_BATT,
    "volts": KIND_BATT,
    "rep": KIND_REP, "rep1": KIND_REP, "rep2": KIND_REP, "repeater": KIND_REP,
    "rptr": KIND_REP,
    "chk": KIND_CHECK, "check": KIND_CHECK,
    "temp": KIND_OTHER, "rh": KIND_OTHER,
}
# "AL"/"ALERT" says nothing about the sensor - never let it decide the kind.
KIND_NEUTRAL = ("al", "alert")
KIND_NEUTRAL_UPPER = frozenset(t.upper() for t in KIND_NEUTRAL)


def kind_of(text):
    """Classify a sensor type string / name suffix into a kind code."""
    if not text:
        return KIND_OTHER
    for rx, code in KIND_RULES:
        if rx.search(text):
            return code
    return KIND_OTHER


# --------------------------------------------------------------------------------------
# name cleaning
# --------------------------------------------------------------------------------------

def split_suffix(name):
    """Split trailing marker tokens off a name.

    'Caniaview RN/Rep' -> ('Caniaview', ['RN/Rep']);  'Loudoun Br AL' -> ('Loudoun Br', ['AL']).
    """
    parts = name.split()
    tail = []
    while len(parts) > 1 and SUFFIX_TOKEN.match(parts[-1]):
        tail.append(parts.pop())
    tail.reverse()
    return " ".join(parts), tail


def strip_kind_suffix(name):
    """Drop trailing marker tokens: 'Caniaview RN/Rep' -> 'Caniaview'."""
    return split_suffix(name)[0]


def suffix_kind(tokens, whole):
    """Kind implied by an address-file name's trailing tokens."""
    for tok in tokens:
        low = tok.lower()
        if low in KIND_NEUTRAL:
            continue
        if low in SUFFIX_KIND:
            return SUFFIX_KIND[low]
    meaningful = [t for t in tokens if t.lower() not in KIND_NEUTRAL]
    return kind_of(" ".join(meaningful)) if meaningful else kind_of(whole)


def clean_name(name, limit=NAME_MAX):
    """Uppercase ASCII, restricted charset, whitespace collapsed, truncated to `limit`.

    Commas are outside the charset, so they become spaces: the radio puts names
    into CSV fields."""
    s = strip_kind_suffix(name)
    s = s.upper()
    # fold anything non-ASCII to a space before the charset filter
    s = s.encode("ascii", "replace").decode("ascii").replace("?", " ")
    s = NAME_ALLOWED.sub(" ", s)
    # The "AL"/"ALERT" marker also turns up mid-name, ahead of a parenthesised qualifier
    # ("Walls Camp AL (Pacific Haven)"), where the trailing strip above cannot reach it.
    # Drop it as a standalone token wherever it appears - it never carries any meaning.
    words = [w for w in s.split() if w not in KIND_NEUTRAL_UPPER]
    if not words:
        words = s.split()
    s = " ".join(words)
    s = s[:limit].rstrip()
    return s


# --------------------------------------------------------------------------------------
# source loading
# --------------------------------------------------------------------------------------

def _decode_utf16(data):
    if data[:2] in (b"\xff\xfe", b"\xfe\xff"):
        return data.decode("utf-16")
    try:
        return data.decode("utf-16-le")
    except UnicodeDecodeError:
        return data.decode("utf-8", "replace")


def _fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "quansheng-alert-gen"})
    with urllib.request.urlopen(req, timeout=60) as fh:
        return fh.read()


class Sources(object):
    def __init__(self, stations, addresses, repeaters, sha, short_sha, date):
        self.stations = stations       # parsed json
        self.addresses = addresses     # decoded text
        self.repeaters = repeaters     # decoded text
        self.sha = sha
        self.short_sha = short_sha
        self.date = date


def _git(dirpath, *args):
    try:
        out = subprocess.run(
            ["git", "-C", dirpath] + list(args),
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, check=True,
        )
        return out.stdout.decode("utf-8", "replace").strip()
    except Exception:
        return ""


def load_sources(meganet_dir, ref):
    if meganet_dir:
        base = os.path.abspath(meganet_dir)
        with open(os.path.join(base, STATIONS_JSON), "rb") as fh:
            stations = json.loads(fh.read().decode("utf-8-sig"))
        with open(os.path.join(base, ADDRESS_FILE), "rb") as fh:
            addresses = _decode_utf16(fh.read())
        with open(os.path.join(base, REPEATERS_CSV), "rb") as fh:
            repeaters = fh.read().decode("utf-8-sig")
        sha = _git(base, "rev-parse", "HEAD") or ref
        short = _git(base, "rev-parse", "--short", "HEAD") or ref
        # commit date keeps the header byte-stable between runs (important for --check)
        date = _git(base, "log", "-1", "--format=%cd", "--date=format-local:%Y-%m-%d")
        if not date:
            date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        return Sources(stations, addresses, repeaters, sha, short, date)

    raw = RAW_BASE.format(ref=ref)
    stations = json.loads(_fetch(raw + STATIONS_JSON).decode("utf-8-sig"))
    addresses = _decode_utf16(_fetch(raw + ADDRESS_FILE_URL))
    repeaters = _fetch(raw + REPEATERS_CSV).decode("utf-8-sig")
    sha, short, date = ref, ref, datetime.now(timezone.utc).strftime("%Y-%m-%d")
    try:
        info = json.loads(_fetch(API_COMMIT.format(ref=ref)).decode("utf-8"))
        sha = info.get("sha") or ref
        short = sha[:7]
        iso = (info.get("commit", {}).get("committer", {}) or {}).get("date")
        if iso:
            date = iso[:10]
    except (urllib.error.URLError, urllib.error.HTTPError, ValueError, KeyError):
        pass  # offline / rate limited - fall back to the ref itself
    return Sources(stations, addresses, repeaters, sha, short, date)


# --------------------------------------------------------------------------------------
# parsing
# --------------------------------------------------------------------------------------

class Record(object):
    """One ALERT address with everything needed to filter and group it."""

    __slots__ = ("aid", "kind", "name", "full_name", "group", "pri", "order",
                 "networks", "catchments")

    def __init__(self, aid, kind, name, full_name, group, pri, order,
                 networks, catchments):
        self.aid = aid
        self.kind = kind
        self.name = name
        self.full_name = full_name
        self.group = group
        self.pri = pri
        self.order = order
        self.networks = networks
        self.catchments = catchments


ALERT_IDS_KIND = [("rainfall", KIND_RAIN), ("water_level", KIND_LEVEL),
                  ("battery", KIND_BATT)]


def parse_repeaters(text):
    """-> {network name: [(lo, hi), ...]} from the BoM Network / pass range columns."""
    nets = {}
    reader = csv.DictReader(io.StringIO(text))

    def num(v):
        v = (v or "").strip()
        if not v:
            return None
        try:
            return int(float(v))
        except ValueError:
            return None

    for row in reader:
        net = (row.get("BoM Network") or "").strip()
        if not net:
            continue
        for i in range(1, 9):
            lo = num(row.get("Pass low %d" % i))
            hi = num(row.get("Pass high %d" % i))
            if lo is None or hi is None:
                continue
            if lo > hi:
                lo, hi = hi, lo
            nets.setdefault(net, []).append((lo, hi))
    for net in nets:
        nets[net] = sorted(set(nets[net]))
    return nets


def networks_for_id(aid, repeater_nets):
    return set(net for net, ranges in repeater_nets.items()
               if any(lo <= aid <= hi for lo, hi in ranges))


def parse_stations_json(doc, repeater_nets, name_limit=NAME_MAX):
    """One Record per (station, alert address). Priority 0 - wins over the address file."""
    net_name = {n["id"]: n.get("name", n["id"]) for n in doc.get("radio_networks", [])}
    cat_name = {c["id"]: c.get("name", c["id"]) for c in doc.get("catchments", [])}
    records = []
    order = 0
    for st in doc.get("stations", []):
        raw = (st.get("name") or st.get("id") or "").strip()
        if not raw:
            continue
        kinds = {}  # aid -> kind, first non-OTHER wins
        for sensor in st.get("sensors") or []:
            aid = sensor.get("alert_id")
            if not isinstance(aid, int):
                continue
            k = kind_of(sensor.get("type") or "")
            if aid not in kinds or (kinds[aid] == KIND_OTHER and k != KIND_OTHER):
                kinds[aid] = k
        for key, k in ALERT_IDS_KIND:
            aid = (st.get("alert_ids") or {}).get(key)
            if not isinstance(aid, int):
                continue
            if aid not in kinds or (kinds[aid] == KIND_OTHER and k != KIND_OTHER):
                kinds[aid] = k

        st_nets = set()
        for nid in st.get("radio_network_ids") or []:
            st_nets.add(nid)
            st_nets.add(net_name.get(nid, nid))
        cats = set()
        for cid in st.get("catchment_ids") or []:
            cats.add(cid)
            cats.add(cat_name.get(cid, cid))

        group = "S:" + (st.get("id") or raw) + ":%d" % order
        name = clean_name(raw, name_limit)
        if not name:
            continue
        for aid in sorted(kinds):
            if not (0 < aid <= MAX_ALERT_ID):
                continue
            nets = set(st_nets) | networks_for_id(aid, repeater_nets)
            records.append(Record(aid, kinds[aid] or KIND_OTHER, name, raw, group,
                                  0, order, nets, cats))
        order += 1
    return records


ADDR_LINE = re.compile(r"^\s*(\d+)\s+(.*\S)")


def parse_address_file(text, repeater_nets, name_limit=NAME_MAX):
    """Records from the legacy address file. Priority 1 - fallback only."""
    rows = []
    for line in text.splitlines():
        if not line.startswith(" "):
            continue  # the file's own convention: comments do not start with a space
        m = ADDR_LINE.match(line)
        if not m:
            continue
        aid = int(m.group(1))
        if not (0 < aid <= MAX_ALERT_ID):
            continue
        rows.append((aid, m.group(2).strip()))
    rows.sort(key=lambda r: r[0])

    records = []
    prev_name = None
    gidx = 0
    for order, (aid, raw) in enumerate(rows):
        name = clean_name(raw, name_limit)
        if not name:
            continue
        # consecutive rows sharing the cleaned name prefix belong to one site group
        if name != prev_name:
            gidx += 1
            prev_name = name
        group = "A:%s:%d" % (name, gidx)
        kind = suffix_kind(split_suffix(raw)[1], raw)
        nets = networks_for_id(aid, repeater_nets)
        records.append(Record(aid, kind, name, raw, group, 1, order, nets, set()))
    return records


# --------------------------------------------------------------------------------------
# filter
# --------------------------------------------------------------------------------------

class Filter(object):
    def __init__(self):
        self.include = []   # (kind, arg)
        self.exclude = []

    @property
    def empty(self):
        return not self.include

    @staticmethod
    def parse(path):
        f = Filter()
        with open(path, "r", encoding="utf-8") as fh:
            for lineno, line in enumerate(fh, 1):
                line = line.split("#", 1)[0].strip()
                if not line:
                    continue
                target = f.include
                if line.lower().startswith("exclude "):
                    target = f.exclude
                    line = line[len("exclude "):].strip()
                parts = line.split(None, 1)
                verb = parts[0].lower()
                arg = parts[1].strip() if len(parts) > 1 else ""
                if verb == "all":
                    target.append(("all", None))
                elif verb == "range":
                    m = re.match(r"^(\d+)\s*-\s*(\d+)$", arg)
                    if not m:
                        raise SystemExit("%s:%d: bad range %r" % (path, lineno, arg))
                    lo, hi = int(m.group(1)), int(m.group(2))
                    target.append(("range", (min(lo, hi), max(lo, hi))))
                elif verb == "id":
                    target.append(("id", int(arg)))
                elif verb in ("network", "catchment", "station"):
                    if not arg:
                        raise SystemExit("%s:%d: %s needs an argument" % (path, lineno, verb))
                    target.append((verb, arg.lower()))
                else:
                    raise SystemExit("%s:%d: unknown directive %r" % (path, lineno, verb))
        return f

    @staticmethod
    def _match(rule, rec):
        kind, arg = rule
        if kind == "all":
            return True
        if kind == "range":
            return arg[0] <= rec.aid <= arg[1]
        if kind == "id":
            return rec.aid == arg
        if kind == "network":
            return any(arg in n.lower() for n in rec.networks)
        if kind == "catchment":
            return any(arg in c.lower() for c in rec.catchments)
        if kind == "station":
            return arg in rec.full_name.lower() or arg in rec.name.lower()
        return False

    def keep(self, rec):
        if not any(self._match(r, rec) for r in self.include):
            return False
        return not any(self._match(r, rec) for r in self.exclude)


# --------------------------------------------------------------------------------------
# table construction
# --------------------------------------------------------------------------------------

def _same_site(a, b):
    """Two cleaned names that only differ by a trailing qualifier / 13-char truncation."""
    return a.startswith(b) or b.startswith(a)


def dedupe(records):
    """ALERT addresses are unique only per region. Keep the first claimant.

    Order is (source priority, source order, address) so the result is deterministic.
    Returns (kept records, collisions) where collisions is a list of
    (aid, winner name, [loser names]) covering only genuine conflicts - a loser whose
    name is a prefix variant of the winner is the same site described by both sources
    and is counted in `benign` instead.
    """
    ordered = sorted(records, key=lambda r: (r.pri, r.order, r.aid))
    winner = {}
    losers = {}
    benign = 0
    for rec in ordered:
        if rec.aid in winner:
            if rec.name != winner[rec.aid].name:
                if _same_site(rec.name, winner[rec.aid].name):
                    benign += 1
                else:
                    losers.setdefault(rec.aid, []).append(rec.name)
            continue
        winner[rec.aid] = rec
    collisions = []
    for aid in sorted(losers):
        seen = []
        for n in losers[aid]:
            if n not in seen and not _same_site(n, winner[aid].name):
                seen.append(n)
        if seen:
            collisions.append((aid, winner[aid].name, seen))
    return [winner[a] for a in sorted(winner)], collisions, benign


class Site(object):
    __slots__ = ("base", "kinds", "name", "members")

    def __init__(self, base, name):
        self.base = base
        self.name = name
        self.kinds = 0
        self.members = []  # (aid, kind)

    def add(self, aid, kind):
        self.kinds |= (kind & 7) << (3 * (aid - self.base))
        self.members.append((aid, kind))


def build_sites(records):
    """Group records into sites of up to 5 consecutive addresses (base..base+4).

    A site takes the smallest remaining address of its group as the base and absorbs the
    group's further addresses that land inside the window. The walk is over the globally
    sorted address list rather than one group at a time, so a site is always a contiguous
    slice of that list and can never claim an address at or beyond the next site's base.
    That matters: the C side binary-searches for the greatest base_id <= id, so a site
    whose window straddled another site's base would make those addresses unreachable
    (2,156 "Three Mile Br" was one of 12 such addresses before this cut was added).
    """
    recs = sorted(records, key=lambda r: (r.aid, r.group))
    sites = []
    cur = None
    cur_group = None
    for rec in recs:
        if cur is None or rec.group != cur_group or rec.aid >= cur.base + SITE_SPAN:
            cur = Site(rec.aid, rec.name)
            cur_group = rec.group
            sites.append(cur)
        cur.add(rec.aid, rec.kind)
    return sites


def build_pool(sites):
    """De-duplicated name pool. Returns (offsets by name, ordered names, byte length)."""
    offsets = {}
    order = []
    total = 0
    for site in sites:
        if site.name not in offsets:
            offsets[site.name] = total
            order.append(site.name)
            total += len(site.name) + 1
    return offsets, order, total


def table_bytes(sites):
    _, _, pool = build_pool(sites)
    return SITE_BYTES * len(sites) + pool


def cost_of(records):
    if not records:
        return 0, 0, 0
    sites = build_sites(records)
    return len(sites), len(records), table_bytes(sites)


# --------------------------------------------------------------------------------------
# emitting
# --------------------------------------------------------------------------------------

def c_escape(s):
    out = []
    for ch in s:
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        else:
            out.append(ch)
    return "".join(out)


def table_fingerprint(sites, offsets, pool_order):
    """A short hash of the table this header will contain.

    Deliberately *not* MegaNet's commit id. The radio shows this string, and a
    build is rewritten whenever it changes, so it has to identify the station
    data itself - otherwise every unrelated commit in MegaNet would produce a
    "new" firmware carrying an identical table. Which MegaNet commit the data
    came from is recorded in docs/firmware/manifest.json instead.
    """
    h = hashlib.sha256()
    for site in sites:
        h.update(("%d,%d,%s;" % (site.base, site.kinds, site.name)).encode())
    for name in pool_order:
        h.update(("%d:%s;" % (offsets[name], name)).encode())
    return h.hexdigest()[:7]


def render_header(sites, src, filter_path):
    offsets, pool_order, pool_len = build_pool(sites)
    addresses = sum(len(s.members) for s in sites)
    total = SITE_BYTES * len(sites) + pool_len
    fingerprint = table_fingerprint(sites, offsets, pool_order)

    out = []
    w = out.append
    w("// GENERATED FILE - do not edit. Regenerate with: python3 tools/gen_stations.py")
    w("// Source: %s  filter: %s" % (REPO, filter_path))
    w("// Sites: %d   Addresses covered: %d   Table bytes: %d   Data: %s"
      % (len(sites), addresses, total, fingerprint))
    w("//")
    w("// The MegaNet commit this was generated from is recorded in")
    w("// docs/firmware/manifest.json, not here: it changes on every unrelated")
    w("// push to MegaNet, and anything in this file ends up in the firmware image.")
    w("#pragma once")
    w("#include <stdint.h>")
    w("#define ALERT_STATIONS_COUNT %d" % len(sites))
    w('#define ALERT_STATIONS_SOURCE "MegaNet:%s"' % fingerprint)
    w('// One entry per "site": a base ALERT id plus up to 5 consecutive addresses '
      "(base..base+4).")
    w("// kinds packs 3 bits per offset: bits 0-2 = base+0, bits 3-5 = base+1, "
      "... bits 12-14 = base+4.")
    w("// kind codes: 0 none, 1 RAIN, 2 LEVEL, 3 BATT, 4 REP, 5 OTHER, 6 CHECK")
    w("typedef struct { uint16_t base_id; uint16_t kinds; uint16_t name_off; } AlertSite_t;")
    w("static const AlertSite_t gAlertSites[ALERT_STATIONS_COUNT] = {")
    for site in sites:
        detail = ", ".join("%d %s" % (aid, KIND_NAME[k]) for aid, k in site.members)
        w("\t{ %4d, 0x%04x, %5d }, // %s  (%s)"
          % (site.base, site.kinds, offsets[site.name], site.name, detail))
    w("};")
    w("static const char gAlertNames[] =")
    for name in pool_order:
        w('\t"%s\\0"' % c_escape(name))
    if not pool_order:
        w('\t""')
    w("\t;")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------------------
# the SPI-flash blob (--blob / --check-blob)
# --------------------------------------------------------------------------------------

def build_blob(sites, source):
    """The V2_SPEC section 8 blob for `sites` (build_sites output, full names)."""
    offsets, pool_order, pool_len = build_pool(sites)
    body = bytearray()
    for site in sites:
        body += BLOB_SITE.pack(site.base, site.kinds, offsets[site.name])
    for name in pool_order:
        body += name.encode("ascii") + b"\0"
    assert len(body) == BLOB_SITE.size * len(sites) + pool_len
    src = source.encode("ascii")[:15].ljust(16, b"\0")
    head = BLOB_HEADER.pack(BLOB_MAGIC, BLOB_VERSION, len(sites), pool_len,
                            zlib.crc32(bytes(body)) & 0xFFFFFFFF, src)
    return head + bytes(body)


def _blob_parts(data):
    magic, version, count, names_len, crc, src = BLOB_HEADER.unpack_from(data, 0)
    sites_at = BLOB_HEADER.size
    names_at = sites_at + BLOB_SITE.size * count
    return magic, version, count, names_len, crc, src, sites_at, names_at


def blob_lookup(data, aid):
    """alert_stn.c's SpiFind in Python: (name, kind) or None."""
    _, _, count, _, _, _, sites_at, names_at = _blob_parts(data)
    lo, hi, hit = 0, count - 1, None
    while lo <= hi:
        mid = (lo + hi) // 2
        base, kinds, off = BLOB_SITE.unpack_from(data, sites_at + BLOB_SITE.size * mid)
        if base <= aid:
            hit = (base, kinds, off)
            lo = mid + 1
        else:
            hi = mid - 1
    if hit is None or aid - hit[0] >= SITE_SPAN:
        return None
    kind = (hit[1] >> (3 * (aid - hit[0]))) & 7
    if kind == KIND_NONE:
        return None
    start = names_at + hit[2]
    raw = data[start:start + BLOB_NAME_MAX + 1]
    return raw.split(b"\0", 1)[0].decode("ascii"), kind


def check_blob(data):
    """Every rule the firmware relies on. Returns (problems, summary)."""
    problems = []
    if len(data) < BLOB_HEADER.size + BLOB_SITE.size:
        return ["only %d bytes" % len(data)], None
    magic, version, count, names_len, crc, src, sites_at, names_at = _blob_parts(data)
    if magic != BLOB_MAGIC:
        problems.append("magic %r" % magic)
    if version != BLOB_VERSION:
        problems.append("version %d" % version)
    if not 0 < count < 0xFFFF:
        problems.append("count %d" % count)
    if len(data) > BLOB_MAX_BYTES:
        problems.append("%d bytes, over the %d-byte region" % (len(data), BLOB_MAX_BYTES))
    if names_at + names_len != len(data):
        problems.append("header says %d bytes, file has %d" % (names_at + names_len, len(data)))
    if problems:
        return problems, None
    if zlib.crc32(data[BLOB_HEADER.size:]) & 0xFFFFFFFF != crc:
        problems.append("body CRC32 %08X, header says %08X"
                        % (zlib.crc32(data[BLOB_HEADER.size:]) & 0xFFFFFFFF, crc))
    source = src.split(b"\0", 1)[0]
    if src[15:] != b"\0" or not re.match(rb"^[!-+\--~]+$", source or b","):
        problems.append("source %r: printable, no spaces or commas, NUL-terminated" % src)

    names = data[names_at:]
    if names and names[-1:] != b"\0":
        problems.append("names do not end with a NUL")
    expected = {}
    prev_base = -1
    for i in range(count):
        base, kinds, off = BLOB_SITE.unpack_from(data, sites_at + BLOB_SITE.size * i)
        where = "site %d (base %d)" % (i, base)
        if base <= prev_base:
            problems.append("%s: not sorted after %d" % (where, prev_base))
        if base > MAX_ALERT_ID:
            problems.append("%s: base over 13 bits" % where)
        if kinds == 0 or kinds >> 15:
            problems.append("%s: kinds 0x%04x" % (where, kinds))
        if off >= names_len:
            problems.append("%s: name_off %d past the names" % (where, off))
            continue
        end = names.find(b"\0", off)
        name = names[off:end].decode("ascii", "replace")
        if not 0 < len(name) <= BLOB_NAME_MAX or not BLOB_NAME_OK.match(name):
            problems.append("%s: name %r" % (where, name))
        for k in range(SITE_SPAN):
            kind = (kinds >> (3 * k)) & 7
            if kind > KIND_CHECK:
                problems.append("%s: kind code %d" % (where, kind))
            if kind:
                if base + k in expected:
                    problems.append("%s: address %d claimed twice" % (where, base + k))
                expected[base + k] = (name, kind)
        prev_base = base
    # The firmware's own search over every address, against the table read
    # directly: it finds the greatest base <= id, so a window that reached
    # past the next site's base would show up here as a wrong answer.
    for aid in range(MAX_ALERT_ID + 1):
        got = blob_lookup(data, aid)
        if got != expected.get(aid):
            problems.append("id %d: lookup gives %r, the table says %r" % (aid, got, expected.get(aid)))
            if len(problems) > 40:
                break
    summary = ("%s: %d sites, %d addresses, %d bytes of names, %d bytes (%.1f%% of 128 KB), "
               "crc %08X" % (source.decode("ascii", "replace"), count, len(expected), names_len,
                             len(data), 100.0 * len(data) / BLOB_MAX_BYTES, crc))
    return problems, summary


# --------------------------------------------------------------------------------------
# reporting
# --------------------------------------------------------------------------------------

def network_costs(records, repeater_nets, doc):
    """[(name, station count, address count, sites, bytes)] sorted by bytes desc."""
    names = set(repeater_nets)
    for n in doc.get("radio_networks", []):
        names.add(n.get("name", n["id"]))
    rows = []
    for name in sorted(names):
        low = name.lower()
        sel = [r for r in records if any(low in n.lower() for n in r.networks)]
        if not sel:
            rows.append((name, 0, 0, 0, 0))
            continue
        sites, addrs, byts = cost_of(sel)
        stations = len(set(r.group for r in sel))
        rows.append((name, stations, addrs, sites, byts))
    rows.sort(key=lambda r: (-r[4], r[0]))
    return rows


def catchment_costs(records, doc):
    names = set()
    for c in doc.get("catchments", []):
        names.add(c.get("name", c["id"]))
    rows = []
    for name in sorted(names):
        low = name.lower()
        sel = [r for r in records if any(low in c.lower() for c in r.catchments)]
        if not sel:
            continue
        sites, addrs, byts = cost_of(sel)
        rows.append((name, len(set(r.group for r in sel)), addrs, sites, byts))
    rows.sort(key=lambda r: (-r[4], r[0]))
    return rows


def print_table(title, rows, limit=None):
    print("")
    print(title)
    print("  %-28s %8s %8s %8s %9s" % ("name", "stations", "addrs", "sites", "bytes"))
    for row in (rows[:limit] if limit else rows):
        print("  %-28s %8d %8d %8d %9d" % row)


# --------------------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------------------

def main(argv=None):
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--meganet-dir", default=os.environ.get("MEGANET_DIR"),
                    help="local MegaNet checkout (default: $MEGANET_DIR, else fetch)")
    ap.add_argument("--meganet-ref", default="main", help="git ref to fetch (default main)")
    ap.add_argument("--filter", default=os.path.join(here, "stations.filter"))
    ap.add_argument("--out", default=os.path.join(here, "app", "alert_stations_gen.h"))
    ap.add_argument("--max-bytes", type=int, default=8000)
    ap.add_argument("--list-networks", action="store_true",
                    help="print per-network / per-catchment costs and exit")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the output would change (for CI)")
    ap.add_argument("--provenance-out", default=None,
                    help="write the MegaNet commit and date here as JSON. That "
                         "provenance is deliberately kept out of the generated "
                         "header, because anything in the header ends up in the "
                         "firmware image and would rewrite it on every unrelated "
                         "MegaNet push")
    ap.add_argument("--blob", metavar="OUT",
                    help="write the SPI-flash station table (V2_SPEC section 8) to OUT "
                         "instead of the header: full names, up to 128 KB")
    ap.add_argument("--all", action="store_true",
                    help="every address MegaNet knows, instead of --filter")
    ap.add_argument("--check-blob", metavar="FILE",
                    help="validate a blob written by --blob and exit (no MegaNet needed)")
    ap.add_argument("--lookup", type=int, action="append", default=[],
                    help="with --check-blob: print what the radio would show for this id")
    args = ap.parse_args(argv)

    if args.check_blob:
        with open(args.check_blob, "rb") as fh:
            data = fh.read()
        problems, summary = check_blob(data)
        for p in problems[:40]:
            print("BAD: " + p)
        if summary:
            print(summary)
        for aid in args.lookup:
            hit = blob_lookup(data, aid) if summary else None
            print("  %5d  %s" % (aid, "%s (%s)" % (hit[0], KIND_NAME[hit[1]]) if hit else "not in the table"))
        print("OK" if not problems else "%d problem(s)" % len(problems))
        return 1 if problems else 0

    name_limit = BLOB_NAME_MAX if args.blob else NAME_MAX
    src = load_sources(args.meganet_dir, args.meganet_ref)
    repeater_nets = parse_repeaters(src.repeaters)
    records = (parse_stations_json(src.stations, repeater_nets, name_limit)
               + parse_address_file(src.addresses, repeater_nets, name_limit))
    universe, collisions, benign = dedupe(records)

    if args.list_networks:
        print("MegaNet %s @ %s (%s)" % (REPO, src.short_sha, src.date))
        sites, addrs, byts = cost_of(universe)
        print("Universe: %d sites, %d addresses, %d bytes (everything)"
              % (sites, addrs, byts))
        print_table("Networks (radio_networks + ALL_REPEATERS.csv pass ranges):",
                    network_costs(universe, repeater_nets, src.stations))
        print_table("Catchments:", catchment_costs(universe, src.stations))
        return 0

    if args.all:
        filt = Filter()
        filt.include.append(("all", None))
        args.filter = "all"
    else:
        filt = Filter.parse(args.filter)
    if filt.empty:
        raise SystemExit("%s contains no include directives - nothing to generate"
                         % args.filter)
    selected = [r for r in universe if filt.keep(r)]
    if not selected:
        raise SystemExit("filter %s selected no addresses" % args.filter)

    sites = build_sites(selected)
    bases = [s.base for s in sites]
    assert bases == sorted(bases), "sites must be sorted by base_id"
    assert len(set(bases)) == len(bases), "duplicate base_id in table"

    if args.blob:
        data = build_blob(sites, "MegaNet:" + src.short_sha[:7])
        problems, summary = check_blob(data)
        if problems:
            for p in problems[:40]:
                print("BAD: " + p)
            raise SystemExit("the blob fails its own checks - not written")
        with open(args.blob, "wb") as fh:
            fh.write(data)
        print("MegaNet %s @ %s (%s)   filter: %s" % (REPO, src.short_sha, src.date, args.filter))
        print(summary)
        print("Wrote %s (upload: STN BEGIN %d %08X)" % (args.blob, len(data), zlib.crc32(data) & 0xFFFFFFFF))
        return 0

    text = render_header(sites, src, os.path.basename(args.filter))
    total = table_bytes(sites)
    addresses = sum(len(s.members) for s in sites)

    if args.provenance_out:
        m = re.search(r"Data: (\w+)", text)
        os.makedirs(os.path.dirname(os.path.abspath(args.provenance_out)) or ".", exist_ok=True)
        with open(args.provenance_out, "w") as fh:
            json.dump({"repo": REPO, "commit": src.short_sha, "commit_full": src.sha,
                       "date": src.date, "filter": os.path.basename(args.filter),
                       "sites": len(sites), "addresses": addresses, "bytes": total,
                       "fingerprint": m.group(1) if m else None}, fh, indent=2)
            fh.write("\n")
        print("Wrote %s" % args.provenance_out)

    net_rows = network_costs(selected, repeater_nets, src.stations)

    if collisions:
        print("WARNING: %d ALERT addresses are claimed by more than one site (ALERT "
              "addresses are only unique per region). Kept the first by source priority "
              "(stations.json before the address file):" % len(collisions))
        for aid, win, others in collisions[:30]:
            print("  %5d  kept %-13s  dropped %s" % (aid, win, ", ".join(others[:3])))
        if len(collisions) > 30:
            print("  ... and %d more" % (len(collisions) - 30))
    if benign:
        print("(%d further duplicate addresses were the same site named slightly "
              "differently by the two sources; not listed.)" % benign)

    print("")
    print("MegaNet %s @ %s (%s)   filter: %s"
          % (REPO, src.short_sha, src.date, args.filter))
    print("Sites: %d   Addresses covered: %d   Table bytes: %d (limit %d)"
          % (len(sites), addresses, total, args.max_bytes))
    print_table("Top networks by cost (within the current filter):", net_rows, limit=15)

    if total > args.max_bytes:
        print("")
        print("ERROR: table is %d bytes, %d over the --max-bytes limit of %d."
              % (total, total - args.max_bytes, args.max_bytes))
        print("Trim %s - drop or narrow the most expensive networks listed above."
              % args.filter)
        return 2

    if args.check:
        try:
            with open(args.out, "r", encoding="utf-8") as fh:
                current = fh.read()
        except OSError:
            current = None
        if current != text:
            print("")
            print("ERROR: %s is out of date; re-run tools/gen_stations.py" % args.out)
            return 1
        print("")
        print("%s is up to date." % args.out)
        return 0

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("")
    print("Wrote %s" % args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
